baseURL = "http://aaronjohnson.io"
languageCode = "en-us"
title = "Aaron Johnson Senior DevOps Engineer"
theme = "m10c"
paginate = 5

[params]
  description = "Aaron specializes in computer automation, CI/CD pipelined application delivery, and DevOps best practices primarily on Linux and Unix like operating systems"
  avatar = "/img/avatar.jpg"
  author = "Aaron Johnson"

  [[params.social]]
    name = "github"
    url = "https://github.com/acjohnson"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/acjohnson1985"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/johnsonaaronc"
